/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BouncedRecipientDto : Bounced recipient



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BouncedRecipientDto {
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "recipient")]
    pub recipient: String,
    #[serde(rename = "userId")]
    pub user_id: String,
}

impl BouncedRecipientDto {
    /// Bounced recipient
    pub fn new(created_at: String, recipient: String, user_id: String) -> BouncedRecipientDto {
        BouncedRecipientDto {
            created_at,
            id: None,
            recipient,
            user_id,
        }
    }
}


