/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateDomainOptions : Options for creating a domain to use with MailSlurp. You must have ownership access to this domain in order to verify it.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDomainOptions {
    /// The top level domain you wish to use with MailSlurp
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
}

impl CreateDomainOptions {
    /// Options for creating a domain to use with MailSlurp. You must have ownership access to this domain in order to verify it.
    pub fn new() -> CreateDomainOptions {
        CreateDomainOptions {
            domain: None,
        }
    }
}


