/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateAnonymousAliasOptions : Create anonymous email alias options. Email aliases can be used to mask real email addresses behind an ID



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAnonymousAliasOptions {
    /// Email address to be hidden behind alias
    #[serde(rename = "emailAddress", skip_serializing_if = "Option::is_none")]
    pub email_address: Option<String>,
}

impl CreateAnonymousAliasOptions {
    /// Create anonymous email alias options. Email aliases can be used to mask real email addresses behind an ID
    pub fn new() -> CreateAnonymousAliasOptions {
        CreateAnonymousAliasOptions {
            email_address: None,
        }
    }
}


