/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DomainDto : Domain plus verification records and status



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomainDto {
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "isVerified")]
    pub is_verified: bool,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "verificationToken")]
    pub verification_token: String,
}

impl DomainDto {
    /// Domain plus verification records and status
    pub fn new(created_at: String, domain: String, id: String, is_verified: bool, updated_at: String, user_id: String, verification_token: String) -> DomainDto {
        DomainDto {
            created_at,
            domain,
            id,
            is_verified,
            updated_at,
            user_id,
            verification_token,
        }
    }
}


