/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DomainPreview : Preview object for domain entity



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomainPreview {
    #[serde(rename = "catchAllInboxId", skip_serializing_if = "Option::is_none")]
    pub catch_all_inbox_id: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "id")]
    pub id: String,
}

impl DomainPreview {
    /// Preview object for domain entity
    pub fn new(created_at: String, domain: String, id: String) -> DomainPreview {
        DomainPreview {
            catch_all_inbox_id: None,
            created_at,
            domain,
            id,
        }
    }
}


