/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ExpiredInboxDto : Expired inbox



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExpiredInboxDto {
    #[serde(rename = "emailAddress")]
    pub email_address: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "inboxId")]
    pub inbox_id: String,
}

impl ExpiredInboxDto {
    /// Expired inbox
    pub fn new(email_address: String, id: String, inbox_id: String) -> ExpiredInboxDto {
        ExpiredInboxDto {
            email_address,
            id,
            inbox_id,
        }
    }
}


