/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NameServerRecord : Name Server Record



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NameServerRecord {
    #[serde(rename = "priority")]
    pub priority: String,
    #[serde(rename = "raw")]
    pub raw: String,
    #[serde(rename = "recordType")]
    pub record_type: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl NameServerRecord {
    /// Name Server Record
    pub fn new(priority: String, raw: String, record_type: String, value: String) -> NameServerRecord {
        NameServerRecord {
            priority,
            raw,
            record_type,
            value,
        }
    }
}


