/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TestNewInboxForwarderOptions {
    #[serde(rename = "inboxForwarderTestOptions")]
    pub inbox_forwarder_test_options: Box<crate::models::InboxForwarderTestOptions>,
    #[serde(rename = "createInboxForwarderOptions")]
    pub create_inbox_forwarder_options: Box<crate::models::CreateInboxForwarderOptions>,
}

impl TestNewInboxForwarderOptions {
    pub fn new(inbox_forwarder_test_options: crate::models::InboxForwarderTestOptions, create_inbox_forwarder_options: crate::models::CreateInboxForwarderOptions) -> TestNewInboxForwarderOptions {
        TestNewInboxForwarderOptions {
            inbox_forwarder_test_options: Box::new(inbox_forwarder_test_options),
            create_inbox_forwarder_options: Box::new(create_inbox_forwarder_options),
        }
    }
}


